export const USER_INFO = {
    CHANGE_PARAM: 'CHANGE_PARAM',
    DELETE_ADVANTAGE: 'DELETE-ADVANTAGE',
    ADD_ADVANTAGE: 'ADD-ADVANTAGE',
    CHECK_CHANGE: 'CHECK-CHANGE',
    RADIO_CHANGE:'RADIO_CHANGE',
    CHANGE_ADVANTAGE:'CHANGE_ADVANTAGE'
}

